### ISSUE TITLE
What about switching to current release after deploy (i.e symlinking)? 

### ISSUE THREAD

**Issue by GarPit** [michaljach/ember-cli-deploy-scp#1]
Found this. Would be great to mention in README about this folder:

    ... destination(this.readConfig('username') + '@' + this.readConfig('host') + ':' + this.readConfig('path') + '/current/web')

**Comment by FUT** [comment]
yep, vote for that :) I had to read source code to understand the way it symlinks the latest build

**Comment by michaljach** [comment]
Thanks for Your contribution :) Remote directory is now configurable (**remoteDir** property) and is `/current/web` by default
