### ISSUE TITLE
Does not throw if upload fails

### ISSUE THREAD

**Issue by jelhan** [michaljach/ember-cli-deploy-scp#11]
ember-cli-deploy-scp does not fail if upload fails. It seems like everything is okay while build wasn't uploaded. To reproducy simply use `examples.com` as `host`. You won't see any failure. Event not if using `--verbose` option.

**Comment by marceloandrader** [comment]
also doesn't fail if rsync is not installed (I was testing it on a docker image without rsync)

**Comment by christophermlne** [comment]
not only does it not throw an error, it actually indicates the upload was successful (with the --verbose flag)

**Comment by michaljach** [comment]
I am aware of that and saw this lately , will look into it ASAP.

**Comment by michaljach** [comment]
Fixed in 1.0.8. Closing.
