### ISSUE TITLE
Asking for password but doesn't get it right

### ISSUE THREAD

**Issue by tevch** [michaljach/ember-cli-deploy-scp#13]
Hi

It works ok till the point of rsync

Then it asks for a password - i enter it, but no success, asks again

Entering generated rsync command directly does the same - asks for password, though get it ok and uploads

**Comment by bretmorris** [comment]
+1 here. The issue looks to be that it attempts to run the next rsync command before the user has a chance to enter in their password.

**Comment by bretmorris** [comment]
@tevch this pull request solves for me https://github.com/michaljach/ember-cli-deploy-scp/pull/14. Assuming you have the same issue.

**Comment by michaljach** [comment]
#14 merged to master. Solved.

**Comment by jdhines** [comment]
Was this made accessible? I just did a new `ember install` of this package, and it still has the old code.

**Comment by michaljach** [comment]
It is published now. Please `ember install` again :)

**Comment by jdhines** [comment]
Thanks, working now. Getting an rsync code 12 error now and the deploy still fails, but I'm not sure that's any problem with this library. I can ssh into the server with the same credentials, so it may be a port problem, I just have to figure out how to check that.
