### ISSUE TITLE
Disable revisioned uploads

### ISSUE THREAD

**Issue by gossi** [michaljach/ember-cli-deploy-scp#17]
In my case I don't need a revisioned upload. I would like to disable it. Maybe there could be a smarter way to detect if there are any revisions mentioned in the context + configuration option and decide from there whether to upload any revisioned version?

**Comment by sandstrom** [comment]
@gossi I can look into this, can you describe the issue in more detail? How should one determine if revisions are needed? How does other plugins solve this?

**Comment by gossi** [comment]
Some simple thing like:

```js
ENV['scp'] = {
        revisions: true|false
}
```

and would not upload directories by revision if this is `false`.

**Comment by joshuairl** [comment]
+1!  It's getting messy seeing all these revisions in there... is there a way to just delete the older ones... similar to how capistrano can set like max revisions and delete the rest.
