### ISSUE TITLE
Prune repo size

### ISSUE THREAD

**Issue by sandstrom** [michaljach/ember-cli-deploy-scp#21]
I noticed this repo is quite large (~17 mb) because some of the early commits included all the `node_modules` content (which usually isn't version controlled).

Not a major issue, but it would be possible to prune this from the repo history, to reduce the size. Since this entails rewriting all commits, only a repo owner can do this.

https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by michaljach** [comment]
Done, please update your local repo. The repo now weights about 2MB.
