### ISSUE TITLE
DEPRECATION: Addon files were detected but no JavaScript preprocessors were found

### ISSUE THREAD

**Issue by tarponjargon** [michaljach/ember-cli-deploy-scp#30]
Is there an easy fix for this deprecation error?

`DEPRECATION: Addon files were detected in /Volumes/Home/Sites/searchapp/node_modules/ember-cli-deploy-scp/addon, but no JavaScript preprocessors were found for ember-cli-deploy-scp. Please make sure to add a preprocessor (most likely ember-cli-babel) to in dependencies (NOT devDependencies) in ember-cli-deploy-scp's package.json.`

ember-cli: 2.18.2
node: 8.5.0
os: darwin x64

    "ember-cli-deploy": "^1.0.2",
    "ember-cli-deploy-build": "^1.1.1",
    "ember-cli-deploy-scp": "^1.0.11",

**Comment by DuBistKomisch** [comment]
I'm also getting this. Caused by https://github.com/michaljach/ember-cli-deploy-scp/pull/27#issuecomment-347892886.

Maintainers just need to remove the `addon/` folder, since it's empty anyway...

**Comment by DuBistKomisch** [comment]
P.S. For an "easy fix" just `rm -rf node_modules/ember-cli-deploy-scp/addon/`.

**Comment by tarponjargon** [comment]
Cool - thanks so much
