### ISSUE TITLE
Publish ember-cli-deploy-scp plugin on the ember-cli-deploy Plugins Page

### ISSUE THREAD

**Issue by terryroe** [michaljach/ember-cli-deploy-scp#8]
This plugin would be easier to find if it were listed on the [ember-cli-deploy Plugins page](http://ember-cli-deploy.com/docs/v0.6.x/plugins/).  You could also apply to get the version badge in the Compatibility section of that page.

(Fortunately, I thought to do a google search for ember-cli-deploy and scp in order to find your plugin.)

**Comment by michaljach** [comment]
It is listed now ! http://ember-cli-deploy.com/docs/v0.6.x/plugins/
